language: ruby

rvm:
  - 2.5.1

before_install:
  - gem update --system
  - gem install bundler

install:

  # Install Jekyll and dependencies
  - bundle install

script: bundle exec rake site:deploy --quiet

env:
  global:
    secure: qSdraeQiNTG2E4Vr1/pd4uZvnjBZBZHCCvvH8qF85Slk1//khSjmW5uZ+rW4K/I1/FSYk6oJRLjtfwuhyX31cOJTn/0/2x71myf7Z2SpKPLfejgQa9SYjo76/u4qtMqBmMwieYd6p/pKAMSABJJ29sfBU1gNjlP2DthCjhIdHaqXnzf7jUiH1N+ug3YHqwLdhA95Vq5TPvWDqdWJkQ37WjOLjqbFfRZMC8PKUcB0dd7iuEDq0DKxzovEebY3ZbcRRFmop8/FJYyFoK6TJx3Ps4q9E0f7AoYkZmXn2WFsRerKoFxB+6uzE/yC1ZBNa6GKZH1g+LzMHhVW5JRVjvHP1I/19hqCTds/wbifdjaoMz1zDY1JWErXbe4TuxB/5gMVC2J6MgSsOmD8qNDUSpe+MGVye+v2JJ+MTTW/9qtte+Tq8Uh7w4LxezWvGCNxWUnpzjab1NHLmtM79lRrCCh5ceOFfhiWusF7twjJfQZqD0P4IBN9D5SaS2ocAZ46YmEBswWKF0Z+u1fAvh+1xW50VTivQjJdECwaAkVtkBrOofmQlcrjVLlvm72xUCpot2VNZ2d2pXVx1jfY+XOsdobHwWH+eqMsiMQSv6bd7IPVKFOBHweDd1u8oI7y/tI68XkkJyqNIxNzrKDkaSVkgh01hfuBQx11M7QnBlz+nZQJ6TA=
