# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Hammar.dev
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hammar.dev" # the base hostname & protocol for your site
repository: hammar/hammar.github.io

# Build settings
markdown: kramdown

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .gitignore

# Disable GitHub Pages defaults that would otherwise alter the generated output
theme: null
sass:
  style: compact
relative_links:
  enabled: false
titles_from_headings:
  enabled: false
