# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: KarlHammar.com
contact: > # this means to ignore newlines until "baseurl:"
  Room E2413<br />
  Department of Computer Science and Informatics<br />
  School of Engineering, Jönköping University
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://karlhammar.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
