# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: KarlHammar.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://karlhammar.com" # the base hostname & protocol for your site

# Settings for deploy Rake task
destination: ../karlhammar.com/
username: hammar
repo: hammar.github.io
branch: source

# Build settings
markdown: kramdown

# Gems
gems: ['jekyll/scholar']

# Jekyll-scholar configuration
scholar:
  sort_by: year
  order: descending
  type_names: { proceedings: Edited Proceedings }
  group_by: type
  type_order: [thesis, article, incollection, inproceedings, proceedings]
  group_order: ascending
  bibliography_template: bib
  bibliography: bibliography.bib
  bibliography_list_tag: ul
  repository: pdfs

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
  - .gitignore
