# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: KarlHammar.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://karlhammar.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Gems
gems: ['jekyll/scholar']

# Jekyll-scholar configuration
scholar:
  sort_by: year
  order: descending
  group_by: type
  bibliography_template: bib
  bibliography: bibliography.bib
  bibliography_list_tag: ul
  bibliography_list_attributes: {about: "http://karlhammar.com/#karl", rel: "foaf:made"}
  type_names: { proceedings: Edited Proceedings }
  repository: pdfs
